# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install: pip install -r server/requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/server/roseGuarden.py"
  - export FLASK_DEBUG=1

script: flask test
